select u.email, a.photo_url, a.photo_url, v.message, v.created_at, a.member_id
    
from votes v, attendances a, users u
    
where u.flag_status=0 and a.id>@aweek and u.is_deleted=0 and a.status_code=1 and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%drug%'
   or u.flag_status=0 and a.id>@aweek and u.is_deleted=0 and a.status_code=1 and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%fake%' 
   or u.flag_status=0 and a.id>@aweek and u.is_deleted=0 and a.status_code=1 and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%flag%'
   or u.flag_status=0 and a.id>@aweek and u.is_deleted=0 and a.status_code=1 and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%cheat%'
   or u.flag_status=0 and a.id>@aweek and u.is_deleted=0 and a.status_code=1 and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%computer%'
   or u.flag_status=0 and a.id>@aweek and u.is_deleted=0 and a.status_code=1 and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%report%'
   or u.flag_status=0 and a.id>@aweek and u.is_deleted=0 and a.status_code=1 and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%internet%'
   or u.flag_status=0 and a.id>@aweek and u.is_deleted=0 and a.status_code=1 and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%image%'
   or u.flag_status=0 and a.id>@aweek and u.is_deleted=0 and a.status_code=1 and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%google%'
   or u.flag_status=0 and a.id>@aweek and u.is_deleted=0 and a.status_code=1 and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%magazine%' 
   or u.flag_status=0 and a.id>@aweek and u.is_deleted=0 and a.status_code=1 and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%plastic%'
   or u.flag_status=0 and a.id>@aweek and u.is_deleted=0 and a.status_code=1 and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%stock%'
   or u.flag_status=0 and a.id>@aweek and u.is_deleted=0 and a.status_code=1 and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%photo%' 
   or u.flag_status=0 and a.id>@aweek and u.is_deleted=0 and a.status_code=1 and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%pic%'  
   or u.flag_status=0 and a.id>@aweek and u.is_deleted=0 and a.status_code=1 and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%screen%' 
   or u.flag_status=0 and a.id>@aweek and u.is_deleted=0 and a.status_code=1 and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%tv%'    
   order by u.email