select v.message, v.created_at, a.member_id, a.photo_url     
    
from votes v, attendances a, users u
    
where a.created_at>@ayear and u.id=@user_id and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%pickles%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%fake%' 
   or a.created_at>@ayear and u.id=@user_id and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%pickles%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%screen%' 
   or a.created_at>@ayear and u.id=@user_id and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%pickles%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%xploit%' 
   or a.created_at>@ayear and u.id=@user_id and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%pickles%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%flag%'
   or a.created_at>@ayear and u.id=@user_id and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%pickles%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%cheat%'
   or a.created_at>@ayear and u.id=@user_id and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%pickles%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%report%'
   or a.created_at>@ayear and u.id=@user_id and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%pickles%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%internet%'
   or a.created_at>@ayear and u.id=@user_id and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%pickles%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%image%'
   or a.created_at>@ayear and u.id=@user_id and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%pickles%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%google%'
   or a.created_at>@ayear and u.id=@user_id and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%pickles%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%magazine%' 
   or a.created_at>@ayear and u.id=@user_id and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%pickles%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%plastic%'
   or a.created_at>@ayear and u.id=@user_id and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%pickles%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%stock%'
   or a.created_at>@ayear and u.id=@user_id and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%pickles%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%photo%' 
   or a.created_at>@ayear and u.id=@user_id and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%pickles%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%pic%' 
   or a.created_at>@ayear and u.id=@user_id and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%pickles%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%pic%pic%' 
   or a.created_at>@ayear and u.id=@user_id and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%pickles%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%photo%photo%'  
   or a.created_at>@ayear and u.id=@user_id and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%pickles%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%photo%picture%' 
   or a.created_at>@ayear and u.id=@user_id and u.id=a.member_id and a.id=v.voteable_id and v.message not like "%dup%" and v.message not like "%similar%" and v.message not like "%same%" and v.message not like "%double%" and v.message not like "%pickles%" and v.message not like "%vegetable%" and v.message  not like "%repeat%" and v.message like '%pic%photo%' 
   